Repository V-V-K/Hacktoberfest2k18, pull requests merged in 2020-10, with the labels that each got.

#45 JS Script for skipping ads in youtube
  youTubeAutoAdSkip.js
Labels: Hacktoberfest

#42 Update BasicIO.cpp
  BasicIO.cpp
Labels: Hactoberfest-accepted

#41 Create last index using recursion
  last index using recursion
Labels: Hacktoberfest, Hactoberfest-accepted, hacktoberfest-accepted

#40 Create linear search
  linear search
Labels: Hacktoberfest, Hactoberfest-accepted, hacktoberfest-accepted
